config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'pages#about_us'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  get '/about-us', to: 'pages#about_us', as: 'about_us'

  get 'contact-us', to: 'contact_forms#new', as: 'conatct_us'
  post 'contact_forms/create', as: 'create_contact_query'

  get '/gallery', to: 'images#index', as: "gallery"
  get '/gallary/upload', to: 'images#new', as: "new_image"
  post 'images/create', as: "create_image"
  put '/images/update', to: "images#update", as: "update_image"
  post '/images/import', to: 'images#import', as: "import_images"

  get '/image_detail/:id', to: 'images#image_detail', as: 'image_detail'

  get '/images/count', to: 'images#total_count'
  
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '*foo', :format => true, :constraints => {:format => :json}, 
    :to => lambda {|env| [404, {}, ['{"error": "page not found", "code": "404"}']] }, via: :all
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  before_action :authenticate_user!
  
  def new
  	@query = UserQuery.new
  end

  def create
  	@query = UserQuery.new(user_query_params)

    respond_to do |format|
      if @query.save
        ContactMailer.acknowledge_mail(user_query_params[:email]).deliver_later
        format.html { redirect_back fallback_location: create_contact_query_url, notice: "Message sent successfully" }
        format.json { render json: { status: "Success", message: "Successful", code: 200 } }
        format.js
    	else
        format.html { render 'new' }
        format.json { render json: { status: "Failure", message: @query.errors.full_messages, code: 500 } }
        format.js
    	end
    end

  end

  private
    def user_query_params
      params.require(:user_query).permit(:name, :email, :mobile, :description)
    end
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/views/contact_forms/create.js.erb
$('.error-div').remove();
var edit_form = $(".contact-form").find('form');
<% unless @query.errors.present? %>
  edit_form.trigger("reset");
  $('#successModal').modal('show');
<% else %>
  var error_html = "<div class='error-div'>";
  <% @query.errors.full_messages.each do |error| %>
    error_html += "<span class='error'><%= error %></span><br />"
  <% end %>
  error_html += '</div>'

  edit_form.prepend($(error_html));
<% end %>

app/views/contact_forms/new.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12 contact-form">
    <%= form_for @query, url: create_contact_query_path, html: {remote: true, class: "well form-horizontal"} do |f| %>

      <% if @query.errors.any? %>
        <% @query.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>
  
			<fieldset>

				<legend>Contact Us Today!</legend>

				<div class="form-group">
				  <label class="col-md-4 control-label">Name</label>  
				  <div class="col-md-6 inputGroupContainer">
				    <div class="input-group">
				      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
              <%= f.text_field :name, placeholder: "Name", class: "form-control"%>
				    </div>
				  </div>
				</div>

	      <div class="form-group">
				  <label class="col-md-4 control-label">E-Mail</label>  
			    <div class="col-md-6 inputGroupContainer">
			      <div class="input-group">
			        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
              <%= f.text_field :email, placeholder: "Email", class: "form-control"%>
			      </div>
			    </div>
				</div>

				<div class="form-group">
				  <label class="col-md-4 control-label">Phone #</label>  
			    <div class="col-md-6 inputGroupContainer">
			      <div class="input-group">
			        <span class="input-group-addon"><i class="glyphicon glyphicon-earphone"></i></span>
              <%= f.text_field :mobile, placeholder: "Phone", class: "form-control"%>
			      </div>
			    </div>
				</div>

				<div class="form-group">
				  <label class="col-md-4 control-label">Message</label>
			    <div class="col-md-6 inputGroupContainer">
			      <div class="input-group">
			        <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i>  </span>
              <%= f.text_area :description, placeholder: "Message", class: "form-control"%>
			      </div>
			    </div>
				</div>

      	<div class="form-group">
      	  <label class="col-md-4 control-label"></label>
      	  <div class="col-md-6">
          <%= button_tag data: { "disable-with": "Sending..." }, class: "btn btn-warning", type: "submit" do %>
            Send <span class="glyphicon glyphicon-send"></span>
          <% end %>
      	  </div>
      	</div>

	    </fieldset>
	  <% end %>
	</div>

	<div class="col-md-6 col-sm-12 location">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3430.4365143734726!2d76.69023331528314!3d30.70612659396505!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390feefe6ee844c7%3A0xc06ae60367c5ec42!2sQuarkcity+India+Pvt+Ltd.!5e0!3m2!1sen!2sin!4v1496745349465" width="600" height="400" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>

	<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	  <div class="modal-dialog" role="document">
	    <div class="modal-content">
	      <div class="modal-body">
	        <span>Message sent successfully</span>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
</div>