config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'pages#about_us'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  get '/about-us', to: 'pages#about_us', as: 'about_us'

  get 'contact-us', to: 'contact_forms#new', as: 'conatct_us'
  post 'contact_forms/create', as: 'create_contact_query'

  get '/gallery', to: 'images#index', as: "gallery"
  get '/gallary/upload', to: 'images#new', as: "new_image"
  post 'images/create', as: "create_image"
  put '/images/update', to: "images#update", as: "update_image"
  post '/images/import', to: 'images#import', as: "import_images"

  get '/image_detail/:id', to: 'images#image_detail', as: 'image_detail'

  get '/images/count', to: 'images#total_count'
  
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '*foo', :format => true, :constraints => {:format => :json}, 
    :to => lambda {|env| [404, {}, ['{"error": "page not found", "code": "404"}']] }, via: :all
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  
  def index
  	@images = MyImage.order(created_at: :desc).page params[:page]
  end

  def new
  	@image = MyImage.new
  end

  def create
  	@image = MyImage.new(name: params['my_image'][:name], image: params['my_image'][:image])
  	respond_to do |format|
      if @image.save
        format.html { redirect_to gallery_path, notice: 'Image uploaded successfully'}
        format.json { render json: { status: "Success", message: "Successful", code: 200 } }
      else
        format.html { render 'new' }
        format.json { render json: { status: "Failure", message: @image.errors.full_messages, code: 500 } }
      end
    end
  end

  def update
  	@image = MyImage.find_by_id(params[:id])

  	if @image
  		@image.name = params['my_image'][:name]
  		unless @image.save
  			@errors = @image.errors.full_messages
  		end
  	else
  		@errors = ["No such image found."]
  	end

  	respond_to do |format|
  		format.js
  	end
  end

  def import
    response = MyImage.import(params[:file])
    unless response[:error_message].present?
      message_string = "#{response[:success]} files imported successfully.<br/>"
      message_string += "#{response[:failed]} files failed to import."
      if response[:failed] > 0
        message_string += "<br /> Failed images detail:<br />"
        response[:failed_rows].each do |row|
          message_string += "Row Id: #{row.keys[0]} <br />"
          row[row.keys[0]].each do |message|
            message_string += message + "<br />"
          end
        end
      end
      flash[:notice] = message_string
      redirect_to gallery_path
    else
      @image = MyImage.new
      flash.now[:error] = response[:error_message]
      render 'new'
    end
  end

  def image_detail
    # checking if image id contains non numeric character
    if params[:id].match(/\A\d+\z/i).blank? # means it does have some non numeric character
      message = "Image id can be numeric only"
      respond_to do |format|
        format.html { redirect_to gallery_path, notice: message }
        format.json { render json: { status: "Failure", message: message, code: 500 } }
      end
    else
      @image = MyImage.find_by_id(params[:id])

      respond_to do |format|
        if @image.present?
          format.html
          format.json { 
            render json: { 
              status: "Success",
              message: "Successful",
              data: {name: @image.name, url: request.protocol + request.host_with_port + @image.image_url},
              code: 200 
            } 
          }
        else
          format.html { redirect_to gallery_path, notice: "No image found" }
          format.json { render json: { status: "Failure", message: "No image found", code: 500 } }
        end
      end
    end
  end

  def total_count
    sleep(1); # To test the loader
    @count = MyImage.all.size

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_image.html.erb
<% cache(image, expires_in: 5.minutes) do %>
  <div class="col-sm-3">
    <%= image_tag image.image_url(:preview) %>
    <br />

    <div class="image-name mt-10">
      <span><%= image.name %></span>
      <button class="edit-btn">Edit</button>
    </div>

    <div class="edit-form-div mt-10" id="<%= image.id%>">
      <%= form_for image, url: update_image_path, method: :put, html: { remote: true, class: "edit_image_form" } do |f| %>
        <%= hidden_field_tag :id, image.id %>
        <%= f.text_field :name %>
        <br />
        
        <%= f.submit "Update", data: { "disable-with": "Saving..." }, class: "update-btn mt-10" %>
        <button type="button" class="cancel-btn mt-10">Cancel</button>
      <% end %>
    </div>

  </div>
<% end %>

app/views/images/image_detail.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= image_tag @image.image_url, size: "250x250" %>
    <br />

    <div class="image-name mt-10">
      <span><%= @image.name %></span>
    </div>

  </div>
</div>

app/views/images/index.html.erb
<% cache(["gallery", @images.map(&:id), @images.maximum(:updated_at)], expires_in: 5.minutes) do %>
  <div class="row">
    <%= link_to "Upload or Import Image", new_image_path, class: "btn btn-primary mt-10 ml-15 pull-left" %>

    <div class="pull-right mt-10 count-div">
      <span class="red-font">Total image count:</span>
      <span class="count" style="display: none;">0</span>
      <div class="loader" title="2">
        <svg version="1.1" id="loader-1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
           width="40px" height="40px" viewBox="0 0 50 50" style="enable-background:new 0 0 50 50;" xml:space="preserve">
        <path fill="#000" d="M43.935,25.145c0-10.318-8.364-18.683-18.683-18.683c-10.318,0-18.683,8.365-18.683,18.683h4.068c0-8.071,6.543-14.615,14.615-14.615c8.072,0,14.615,6.543,14.615,14.615H43.935z">
          <animateTransform attributeType="xml"
            attributeName="transform"
            type="rotate"
            from="0 25 25"
            to="360 25 25"
            dur="0.6s"
            repeatCount="indefinite"/>
          </path>
        </svg>
      </div>
    </div>

    <div style="clear: both;"></div>
    <br />
  	<% if @images.present? %>

      <%= render partial: "image", collection: @images, cached: true %>

      <div style="clear: both;"></div>
      <br />
  		<%= paginate @images %>
  	<% else %>
      <div>
    		<p> No images available</p>
      </div>
  	<% end %>
  </div>
<% end %>

app/views/images/new.html.erb
<div class="row mt-10">
	<div class="well">

		<% if @image.errors.any? %>
        <% @image.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      <% end %>

	  <%= form_for @image, url: create_image_path, html: { multipart: true } do |f| %>
	  	<div class="input-group width-30">
        <%= f.text_field :name, class: "form-control", placeholder: "Image Name" %>
      </div>
      <br />
	  	<div class="input-group width-30">
        <label class="input-group-btn">
          <span class="btn btn-primary">
             Browse&hellip; <%= f.file_field :image, style: "display: none" %>
          </span>
        </label>
        <input type="text" class="form-control" readonly>
      </div>
	    <%= f.submit "Upload", class: "btn btn-primary mt-10" %>
	  <% end %>
	</div>

  <div class="well">
  <p>Select CSV file with name and url header</p>

    <%= form_tag import_images_path, multipart: true do %>
      <div class="input-group width-30">
        <label class="input-group-btn">
          <span class="btn btn-primary">
             Browse&hellip; <%= file_field_tag :file, style: "display: none", accept: ".csv" %>
          </span>
        </label>
        <input type="text" class="form-control" readonly>
      </div>
      <%= submit_tag "Import", class: "btn btn-primary mt-10" %>
    <% end %>
  </div>
</div>

app/views/images/total_count.js.erb
$(".count").html("<%= @count %>");
$(".count").show();
$(".loader").hide();
var text_node = $(".red-font");
text_node.removeClass("red-font");
text_node.addClass("green-font");

app/views/images/update.js.erb
$('.error-div').remove();
<% unless @errors.present? %>
  var form_div = $("#<%= @image.id %>");
  form_div.hide();
  var name_span = form_div.siblings('.image-name').find('span');
  name_span.text("<%= @image.name %>");
  form_div.siblings('.image-name').show();
<% else %>
  var error_html = "<div class='error-div'>";
  <% @errors.each do |error| %>
    error_html += "<span class='error'><%= error %></span>"
  <% end %>
  error_html += '</div>'

  var edit_form = $("#<%= @image.id %>").find('form');
  edit_form.prepend($(error_html));
<% end %>