config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  root 'pages#about_us'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'registrations', sessions: 'sessions' }

  get '/about-us', to: 'pages#about_us', as: 'about_us'

  get 'contact-us', to: 'contact_forms#new', as: 'conatct_us'
  post 'contact_forms/create', as: 'create_contact_query'

  get '/gallery', to: 'images#index', as: "gallery"
  get '/gallary/upload', to: 'images#new', as: "new_image"
  post 'images/create', as: "create_image"
  put '/images/update', to: "images#update", as: "update_image"
  post '/images/import', to: 'images#import', as: "import_images"

  get '/image_detail/:id', to: 'images#image_detail', as: 'image_detail'

  get '/images/count', to: 'images#total_count'
  
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  match '*foo', :format => true, :constraints => {:format => :json}, 
    :to => lambda {|env| [404, {}, ['{"error": "page not found", "code": "404"}']] }, via: :all
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DemoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="flash_msg">
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>"><%= value.html_safe %></div>
    <% end %>
    </div>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
      
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Demo App</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav">
            <li class="<%= active_class(about_us_path) %>"><%= link_to "About Us", about_us_path %></li>
            <li class="<%= active_class(conatct_us_path) %>"><%= link_to "Contact Us", conatct_us_path %></li>
            <li class="<%= active_class(gallery_path) %>"><%= link_to "Gallery", gallery_path %></li>
          </ul>

          <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
              <li><p class="navbar-text">Welcome, <%= "#{current_user.name}" %></p></li>
              <li><%= link_to('Change Password', edit_user_registration_path) %></li>
              <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

	  <div class="container">

	    <%= yield %>

	    <footer class="footer">
	    	<p>&copy; 2017 Maropost Inc. All rights reserved. | <%= link_to "Contact Us", conatct_us_path %></p>
	  	</footer>
  	</div>
  </body>
</html>